# Make a copy of the file and rename it to `secrets.toml`.

MODEL_API_TOKEN = "Your Model API Key"
MODEL_NAME = "Your Model Name"
MODEL_BASE_URL = "Your Model Base URL"
TAVILY_API_KEY = "Your Tavily API Key"
JINAAI_API_KEY = "Your Jina AI API Key"

[database]
DB_HOST="Your Database Host"
DB_PORT=Your Database Port
DB_USERNAME="Your Database Username"
DB_PASSWORD="Your Database Password"
DB_DATABASE="Your Database Name"
SSL_PATH="Your SSL Path"